### ISSUE TITLE
Add some more <meta> tags

### ISSUE THREAD

**Issue by tannerdolby** [tannerdolby/eleventy-plugin-metagen#11]
The plugin should support a few more meta tags.

- [x] - Add `<meta property="og:locale" />` default `en_US`
- [x] - Add `<meta name=“twitter:url”>`
- [x] - Add `<meta name=“twitter:creator”>`
- [x] - Add `<meta name="og:site_name">`
- [x] - Add `<meta name="og:image:width">`
- [x] - Add `<meta name="og:image:height">`
- [x] - Add options for comments above each card section (Twitter and Open Graph)

I also think maybe giving users an option to mix and match `<meta name="">` and `<meta property="">` for Twitter or Open graph meta tag generation would be a good option. e.g. if they want to use `property` for the Twitter card instead of `name` thats fine too. Although Open graph tags use `property` attribute and Twitter docs recommend using `name`, the Twitter parser does fallback to `property` + `content` so that convinces me this functionality could be useful. - https://developer.twitter.com/en/docs/twitter-for-websites/cards/guides/getting-started

The Open Graph/Facebook meta tags use `<meta name="">` ie the `name` attribute in the docs where the Twitter Card docs use `<meta property="">` ie `property` attribute. 

See this for more context https://stackoverflow.com/questions/22350105/whats-the-difference-between-meta-name-and-meta-property

**Comment by tannerdolby** [comment]
Closed in [10c7a0a](https://github.com/tannerdolby/eleventy-plugin-metagen/commit/10c7a0ae6568e7652e4bec2c787a8c670a0742d8) 🎈
